### ISSUE TITLE
Method profilePictureUrl 

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#10]
How can I view a contact's profile picture?
profilePictureUrl method in typescript

**Comment by donaldjansen** [comment]
I have added the function, sample below
var ppurl = await socket.ProfilePictureUrl("xxx@s.whatsapp.net", ProfilePictureUrlType.Image);

**Comment by viniciusverasdossantos** [comment]
very good
