### ISSUE TITLE
GroupParticipantUpdateModel exception

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#12]
I still haven't figured out the reason. But this error is occurring sometimes...
Whenever it occurred it was at the beginning right after starting the application.

https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/68686af6-c977-4c5b-ba67-13b445da96e4

**Comment by viniciusverasdossantos** [comment]
is not in constructor. 
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/21696039-b2e4-426c-bcaa-d0561ff204cf)

**Comment by viniciusverasdossantos** [comment]
another in same line:

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/15c004d5-aa15-42ea-99f6-414c6faeed02)

**Comment by donaldjansen** [comment]
Hi, I am actually aware of this. I will be implementing the event handlers for these two events in next couple of days, including a check on the events so it does not crash, I am just in the process of finalizing appPatch and ModifyChat

**Comment by viniciusverasdossantos** [comment]
very good. I was going to talk about ModifyPath. Thenk you
