### ISSUE TITLE
SendPresenceUpdate make public

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#14]
I need to update the status by typing. The SendPresenceUpdate method is private. Can you make it public?

 private void SendPresenceUpdate(WAPresence type, string toJid = "")

**Comment by GarethWright** [comment]
This is open source...what's preventing you from making it public yourself?

**Comment by viniciusverasdossantos** [comment]
Nothing...I've already done it...These methods are used by the typescript community...they will definitely need it too. Ideally it should stay in the original branch
