### ISSUE TITLE
Version Differences and TypeScript Integration Plans in BaileysCSharp

### ISSUE THREAD

**Issue by caomfan** [WhiskeySockets/BaileysCSharp#19]
AppVersion 2.2329.9 and typescript Version 2.2403.2, what are the differences between these two versions? Are there plans to implement all TypeScript functionalities in BaileysCSharp?

**Comment by caomfan** [comment]
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/30285397/09b43218-8dc9-432a-a30f-12179b6acf46)
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/30285397/9ddae53a-ce4b-4a11-9f74-a16d2d2b6eb2)

**Comment by donaldjansen** [comment]
Hi The plan is to get it on the same version and have all features available that is in the typescript project. This project is still in early phases in migrating functions. I am currently busy with all the chat modifications (mute, archive, clear messages, etc)

**Comment by caomfan** [comment]
Thank you for all the efforts you've made. I implemented a version of Baileys in C# a while ago, but it wasn't perfect.

**Comment by donaldjansen** [comment]
Trust me, my first 1 month of migration wasn't perfect either. There is still a few "bad approach" code in the current version that needs to be taken care of. especially with the storage system
