### ISSUE TITLE
Contact name on EV.MessageHistory.Set

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#21]
I am synchronizing the contacts through the EV.MessageHistory.Set event. The ContactModel is coming with a blank name. Any tips on what it could be?

**Comment by donaldjansen** [comment]
Hi, this is unfortunately how WA does things, the contacts that you are receiving doesn't have any info in, however later on there is a SyncAction (or multiple) that contains the names. This is already implemented ProcessSyncAction in ChatUtils.cs

**Comment by viniciusverasdossantos** [comment]
thanks I'll try!
