### ISSUE TITLE
PushName null error after scan QR Code.

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#22]
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/d45b61ce-9ef9-40c0-86dc-e25ec41a34ed)

Just when scanning the QR code it started giving this error today. I solved it by changing PushName = notify 
 for PushName = notify ?? "". The problem stopped occurring.

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/4ee3e675-bd89-4371-9c9a-c82746d7adda)

**Comment by donaldjansen** [comment]
Thank you, yeah proto is handling the properties weird. I will add to the repo

**Comment by shargon** [comment]
Close? Seems done
