### ISSUE TITLE
QrCode Not created

### ISSUE THREAD

**Issue by MalikAliQassem** [WhiskeySockets/BaileysCSharp#27]
![image](https://github.com/user-attachments/assets/37ff6f08-4126-4bb2-9241-dc50dd89331e)
![image](https://github.com/user-attachments/assets/59eb26ac-cc40-429e-8d2b-f274d672e0ac)

**Comment by donaldjansen** [comment]
Hi to overcome this issue you can change the line Version in SocketConfig to 
Version = [2, 3000, 1015901307]

I am not ready yet to check in my changes
