### ISSUE TITLE
Stop using JSON.NET

### ISSUE THREAD

**Issue by tcortega** [WhiskeySockets/BaileysCSharp#3]
Great work on the lib; However it seems that you've been using JSON.NET quite a lot and it is really not recommended for modern apps nowadays, it is slow compared to STJ and STJ is already a part of the shared .NET Runtime so no need for extra dependencies.

https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/migrate-from-newtonsoft?pivots=dotnet-9-0

I'd migrate now to avoid future work as the project grows. I can open a PR for that.

**Comment by donaldjansen** [comment]
Thank you this was in the planning to migrate it.
