### ISSUE TITLE
The test project is not running.

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#4]
The test project is not running.
Congratulations on the project!!!

**Comment by donaldjansen** [comment]
Hi Can you elaborate more on this and give more information so I can reproduce your result

**Comment by donaldjansen** [comment]
Were you refering to BaileysCSharp.Tests or WhatsSocketConsole

**Comment by viniciusverasdossantos** [comment]
I downloaded it now and everything works. Very good. I loved this project!
