### ISSUE TITLE
QR the first time this error occurs:

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#7]
When I'm scanning the QR the first time this error occurs:

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/fd4ab1ba-44b8-4cf4-83dc-69c1da0f1795)

Callstack:
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/5db4cd26-707d-47c8-a10b-9b0a28bd32cd)

The type is BaileysCSharp.Core.Models.ContactModel

**Comment by viniciusverasdossantos** [comment]
Debugging I discovered that a contact is coming with a blank ID. This is the reason for the error. Could we ignore these?

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/6f30421d-4f4e-40db-bb16-eb6ef522ae0d)

**Comment by viniciusverasdossantos** [comment]
The problem is along these lines.
message.Key.Participant is coming from an empty string...and not null...so it is considering the empty string!

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/3dc52c70-7aec-4843-a114-d68c7fbed979)

message.Key.Participant:
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/02d97502-5ce5-4b77-85be-3ad752a69053)

message.Key.RemoteJid:
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/3f81484b-d34e-4dbb-b5bb-41cb639e260f)

**Comment by viniciusverasdossantos** [comment]
Solution:
 contacts.Add(new ContactModel()
 {
     ID = string.IsNullOrEmpty(message.Key.Participant) ? message.Key.RemoteJid : message.Key.Participant,
     VerifiedName = message.MessageStubParameters[0]
 });

**Comment by donaldjansen** [comment]
Thank you for the feedback and solution, I have not had this error yet. your thorough debugging is appreciated
