### ISSUE TITLE
Error on SendMessage

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#8]
Error on SendMessage.

Should the SendMessage Method already be working? The error below occurs here.
Is this package already 100% functional?

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/435b4b99-1292-4d2b-a56c-da61e0709458)

**Comment by donaldjansen** [comment]
Sending on my side works 100%, however I have seen this error once before from another user, who also said they are not getting it with the last changes I committed. I have been trying to remake it again but could not.
Can you send to 27797798179@s.whatsapp.net and let me know if you get the same error

**Comment by viniciusverasdossantos** [comment]
pelo que debuguei é ao usar o metodo  GetBinaryNodeChild(item, "key");

O valor da variavel item:
{\"tag\":\"user\",\"attrs\":{\"jid\":\"5521995358833:62@s.whatsapp.net\",\"t\":\"1714289630\"},\"content\":[{\"tag\":\"device-identity\",\"attrs\":{},\"content\":\"ChII0MXEpwoQ48LMqQYYASAAKAAaQGU6j0jQoIHJRVruzVdtCq2IW0/K4V1OmOdOAJ6pthXzhjAaw0ryQcSt3WAM6Ie2oO74WU2JnU8xNlUuZmGrXQkiQI0bwA0OhCtFQz0FWebO37v1s+moOt3nayz7v+Fqs6OqB7thtwkHPP34sLDRqdrG6Xp2yvVx1IH9tEfK0Ub23wo=\"},{\"tag\":\"registration\",\"attrs\":{},\"content\":\"AAAASQ==\"},{\"tag\":\"type\",\"attrs\":{},\"content\":\"BQ==\"},{\"tag\":\"identity\",\"attrs\":{},\"content\":\"LSCM80VuQgiVZd78rU77Q0+FF8AXqHD+Mn0ymJ9p9nU=\"},{\"tag\":\"skey\",\"attrs\":{},\"content\":[{\"tag\":\"id\",\"attrs\":{},\"content\":\"AAAB\"},{\"tag\":\"value\",\"attrs\":{},\"content\":\"SMK0k72KFfYjLyJt2bXg0WiHhAXEWYHH4VnNhEP/OGc=\"},{\"tag\":\"signature\",\"attrs\":{},\"content\":\"Ki4OBysuUSrGyw+AshYqkJtAwb8NoBpIAz5SpshIU99Wan2QtpBfm5NNNNrXLbePi4JZqyZSJes44aXOD4jmAA==\"}]}]}


![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/c3620759-85d2-412d-8186-c84307d58344)

Video Debug:


https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/5ae4d376-50d9-40fb-91fd-6dba8cfeb82d

**Comment by viniciusverasdossantos** [comment]
I managed to make it work by changing these two lines.
I compared it with the typescript code.

1)
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/29c50eb4-8642-4b30-b64c-b84acb5bb11c)


2)
theirEphemeralPubKey?.ToByteString()
![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/42aae98c-e9f8-4c04-a5bc-0538ed6e1138)
