### ISSUE TITLE
GetContentType method of the MessageUtil class to be public instead of internal

### ISSUE THREAD

**Issue by viniciusverasdossantos** [WhiskeySockets/BaileysCSharp#9]
I'm migrating an application to .NET and I needed the GetContentType method of the MessageUtil class to be public instead of internal. I'll need to use it. Can you change it to public?

![image](https://github.com/WhiskeySockets/BaileysCSharp/assets/16549732/884d68bb-129e-4faa-ab1a-e03d9918adb6)

**Comment by donaldjansen** [comment]
Sure, I will have it done today for you.

**Comment by viniciusverasdossantos** [comment]
thank you

**Comment by donaldjansen** [comment]
This adjustment has been made.
However I am not sure if this will achieve what you are looking for, will you let me know what you want to achieve ?
